version: '3.8'

services:
  web:
    image: alexnoalternance/strapontissimo:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    # image: mysql:5.7
    image: alexnoalternance/boutiqueenligne-db:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: strapontissimo
      MYSQL_USER: alex
      MYSQL_PASSWORD: alex
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    # image: phpmyadmin/phpmyadmin
    image: alexnoalternance/boutiqueenligne-phpmyadmin:latest
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data: